// <auto-generated />
namespace Vidly_II.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmembershiptype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmembershiptype));
        
        string IMigrationMetadata.Id
        {
            get { return "202105151604056_add-membership-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
